# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/carlos/Documents/Play/sail-game/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/carlos/Documents/Play/sail-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlos/Documents/Play/sail-game/CMakeFiles /home/carlos/Documents/Play/sail-game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlos/Documents/Play/sail-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sail-game

# Build rule for target.
sail-game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sail-game
.PHONY : sail-game

# fast build rule for target.
sail-game/fast:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/build
.PHONY : sail-game/fast

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

FileUtils.o: FileUtils.cpp.o

.PHONY : FileUtils.o

# target to build an object file
FileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/FileUtils.cpp.o
.PHONY : FileUtils.cpp.o

FileUtils.i: FileUtils.cpp.i

.PHONY : FileUtils.i

# target to preprocess a source file
FileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/FileUtils.cpp.i
.PHONY : FileUtils.cpp.i

FileUtils.s: FileUtils.cpp.s

.PHONY : FileUtils.s

# target to generate assembly for a file
FileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/FileUtils.cpp.s
.PHONY : FileUtils.cpp.s

Line.o: Line.cpp.o

.PHONY : Line.o

# target to build an object file
Line.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Line.cpp.o
.PHONY : Line.cpp.o

Line.i: Line.cpp.i

.PHONY : Line.i

# target to preprocess a source file
Line.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Line.cpp.i
.PHONY : Line.cpp.i

Line.s: Line.cpp.s

.PHONY : Line.s

# target to generate assembly for a file
Line.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Line.cpp.s
.PHONY : Line.cpp.s

Mesh.o: Mesh.cpp.o

.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i

.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s

.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

Plane.o: Plane.cpp.o

.PHONY : Plane.o

# target to build an object file
Plane.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Plane.cpp.o
.PHONY : Plane.cpp.o

Plane.i: Plane.cpp.i

.PHONY : Plane.i

# target to preprocess a source file
Plane.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Plane.cpp.i
.PHONY : Plane.cpp.i

Plane.s: Plane.cpp.s

.PHONY : Plane.s

# target to generate assembly for a file
Plane.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Plane.cpp.s
.PHONY : Plane.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Player.cpp.s
.PHONY : Player.cpp.s

PlayerInputComponent.o: PlayerInputComponent.cpp.o

.PHONY : PlayerInputComponent.o

# target to build an object file
PlayerInputComponent.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/PlayerInputComponent.cpp.o
.PHONY : PlayerInputComponent.cpp.o

PlayerInputComponent.i: PlayerInputComponent.cpp.i

.PHONY : PlayerInputComponent.i

# target to preprocess a source file
PlayerInputComponent.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/PlayerInputComponent.cpp.i
.PHONY : PlayerInputComponent.cpp.i

PlayerInputComponent.s: PlayerInputComponent.cpp.s

.PHONY : PlayerInputComponent.s

# target to generate assembly for a file
PlayerInputComponent.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/PlayerInputComponent.cpp.s
.PHONY : PlayerInputComponent.cpp.s

PointForce.o: PointForce.cpp.o

.PHONY : PointForce.o

# target to build an object file
PointForce.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/PointForce.cpp.o
.PHONY : PointForce.cpp.o

PointForce.i: PointForce.cpp.i

.PHONY : PointForce.i

# target to preprocess a source file
PointForce.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/PointForce.cpp.i
.PHONY : PointForce.cpp.i

PointForce.s: PointForce.cpp.s

.PHONY : PointForce.s

# target to generate assembly for a file
PointForce.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/PointForce.cpp.s
.PHONY : PointForce.cpp.s

RigidObject.o: RigidObject.cpp.o

.PHONY : RigidObject.o

# target to build an object file
RigidObject.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/RigidObject.cpp.o
.PHONY : RigidObject.cpp.o

RigidObject.i: RigidObject.cpp.i

.PHONY : RigidObject.i

# target to preprocess a source file
RigidObject.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/RigidObject.cpp.i
.PHONY : RigidObject.cpp.i

RigidObject.s: RigidObject.cpp.s

.PHONY : RigidObject.s

# target to generate assembly for a file
RigidObject.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/RigidObject.cpp.s
.PHONY : RigidObject.cpp.s

RigidObjectGraphicsComponent.o: RigidObjectGraphicsComponent.cpp.o

.PHONY : RigidObjectGraphicsComponent.o

# target to build an object file
RigidObjectGraphicsComponent.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/RigidObjectGraphicsComponent.cpp.o
.PHONY : RigidObjectGraphicsComponent.cpp.o

RigidObjectGraphicsComponent.i: RigidObjectGraphicsComponent.cpp.i

.PHONY : RigidObjectGraphicsComponent.i

# target to preprocess a source file
RigidObjectGraphicsComponent.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/RigidObjectGraphicsComponent.cpp.i
.PHONY : RigidObjectGraphicsComponent.cpp.i

RigidObjectGraphicsComponent.s: RigidObjectGraphicsComponent.cpp.s

.PHONY : RigidObjectGraphicsComponent.s

# target to generate assembly for a file
RigidObjectGraphicsComponent.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/RigidObjectGraphicsComponent.cpp.s
.PHONY : RigidObjectGraphicsComponent.cpp.s

ShaderMisc.o: ShaderMisc.cpp.o

.PHONY : ShaderMisc.o

# target to build an object file
ShaderMisc.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/ShaderMisc.cpp.o
.PHONY : ShaderMisc.cpp.o

ShaderMisc.i: ShaderMisc.cpp.i

.PHONY : ShaderMisc.i

# target to preprocess a source file
ShaderMisc.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/ShaderMisc.cpp.i
.PHONY : ShaderMisc.cpp.i

ShaderMisc.s: ShaderMisc.cpp.s

.PHONY : ShaderMisc.s

# target to generate assembly for a file
ShaderMisc.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/ShaderMisc.cpp.s
.PHONY : ShaderMisc.cpp.s

SkyParameters.o: SkyParameters.cpp.o

.PHONY : SkyParameters.o

# target to build an object file
SkyParameters.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyParameters.cpp.o
.PHONY : SkyParameters.cpp.o

SkyParameters.i: SkyParameters.cpp.i

.PHONY : SkyParameters.i

# target to preprocess a source file
SkyParameters.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyParameters.cpp.i
.PHONY : SkyParameters.cpp.i

SkyParameters.s: SkyParameters.cpp.s

.PHONY : SkyParameters.s

# target to generate assembly for a file
SkyParameters.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyParameters.cpp.s
.PHONY : SkyParameters.cpp.s

SkyboxObject.o: SkyboxObject.cpp.o

.PHONY : SkyboxObject.o

# target to build an object file
SkyboxObject.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyboxObject.cpp.o
.PHONY : SkyboxObject.cpp.o

SkyboxObject.i: SkyboxObject.cpp.i

.PHONY : SkyboxObject.i

# target to preprocess a source file
SkyboxObject.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyboxObject.cpp.i
.PHONY : SkyboxObject.cpp.i

SkyboxObject.s: SkyboxObject.cpp.s

.PHONY : SkyboxObject.s

# target to generate assembly for a file
SkyboxObject.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyboxObject.cpp.s
.PHONY : SkyboxObject.cpp.s

SkyboxObjectGraphicsComponent.o: SkyboxObjectGraphicsComponent.cpp.o

.PHONY : SkyboxObjectGraphicsComponent.o

# target to build an object file
SkyboxObjectGraphicsComponent.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyboxObjectGraphicsComponent.cpp.o
.PHONY : SkyboxObjectGraphicsComponent.cpp.o

SkyboxObjectGraphicsComponent.i: SkyboxObjectGraphicsComponent.cpp.i

.PHONY : SkyboxObjectGraphicsComponent.i

# target to preprocess a source file
SkyboxObjectGraphicsComponent.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyboxObjectGraphicsComponent.cpp.i
.PHONY : SkyboxObjectGraphicsComponent.cpp.i

SkyboxObjectGraphicsComponent.s: SkyboxObjectGraphicsComponent.cpp.s

.PHONY : SkyboxObjectGraphicsComponent.s

# target to generate assembly for a file
SkyboxObjectGraphicsComponent.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/SkyboxObjectGraphicsComponent.cpp.s
.PHONY : SkyboxObjectGraphicsComponent.cpp.s

TestObject.o: TestObject.cpp.o

.PHONY : TestObject.o

# target to build an object file
TestObject.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/TestObject.cpp.o
.PHONY : TestObject.cpp.o

TestObject.i: TestObject.cpp.i

.PHONY : TestObject.i

# target to preprocess a source file
TestObject.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/TestObject.cpp.i
.PHONY : TestObject.cpp.i

TestObject.s: TestObject.cpp.s

.PHONY : TestObject.s

# target to generate assembly for a file
TestObject.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/TestObject.cpp.s
.PHONY : TestObject.cpp.s

Triangle.o: Triangle.cpp.o

.PHONY : Triangle.o

# target to build an object file
Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Triangle.cpp.o
.PHONY : Triangle.cpp.o

Triangle.i: Triangle.cpp.i

.PHONY : Triangle.i

# target to preprocess a source file
Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Triangle.cpp.i
.PHONY : Triangle.cpp.i

Triangle.s: Triangle.cpp.s

.PHONY : Triangle.s

# target to generate assembly for a file
Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/Triangle.cpp.s
.PHONY : Triangle.cpp.s

TypeSize.o: TypeSize.cpp.o

.PHONY : TypeSize.o

# target to build an object file
TypeSize.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/TypeSize.cpp.o
.PHONY : TypeSize.cpp.o

TypeSize.i: TypeSize.cpp.i

.PHONY : TypeSize.i

# target to preprocess a source file
TypeSize.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/TypeSize.cpp.i
.PHONY : TypeSize.cpp.i

TypeSize.s: TypeSize.cpp.s

.PHONY : TypeSize.s

# target to generate assembly for a file
TypeSize.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/TypeSize.cpp.s
.PHONY : TypeSize.cpp.s

UBOManager.o: UBOManager.cpp.o

.PHONY : UBOManager.o

# target to build an object file
UBOManager.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/UBOManager.cpp.o
.PHONY : UBOManager.cpp.o

UBOManager.i: UBOManager.cpp.i

.PHONY : UBOManager.i

# target to preprocess a source file
UBOManager.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/UBOManager.cpp.i
.PHONY : UBOManager.cpp.i

UBOManager.s: UBOManager.cpp.s

.PHONY : UBOManager.s

# target to generate assembly for a file
UBOManager.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/UBOManager.cpp.s
.PHONY : UBOManager.cpp.s

VertexElementGraphicsComponent.o: VertexElementGraphicsComponent.cpp.o

.PHONY : VertexElementGraphicsComponent.o

# target to build an object file
VertexElementGraphicsComponent.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/VertexElementGraphicsComponent.cpp.o
.PHONY : VertexElementGraphicsComponent.cpp.o

VertexElementGraphicsComponent.i: VertexElementGraphicsComponent.cpp.i

.PHONY : VertexElementGraphicsComponent.i

# target to preprocess a source file
VertexElementGraphicsComponent.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/VertexElementGraphicsComponent.cpp.i
.PHONY : VertexElementGraphicsComponent.cpp.i

VertexElementGraphicsComponent.s: VertexElementGraphicsComponent.cpp.s

.PHONY : VertexElementGraphicsComponent.s

# target to generate assembly for a file
VertexElementGraphicsComponent.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/VertexElementGraphicsComponent.cpp.s
.PHONY : VertexElementGraphicsComponent.cpp.s

WaterSurface.o: WaterSurface.cpp.o

.PHONY : WaterSurface.o

# target to build an object file
WaterSurface.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurface.cpp.o
.PHONY : WaterSurface.cpp.o

WaterSurface.i: WaterSurface.cpp.i

.PHONY : WaterSurface.i

# target to preprocess a source file
WaterSurface.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurface.cpp.i
.PHONY : WaterSurface.cpp.i

WaterSurface.s: WaterSurface.cpp.s

.PHONY : WaterSurface.s

# target to generate assembly for a file
WaterSurface.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurface.cpp.s
.PHONY : WaterSurface.cpp.s

WaterSurfaceGraphicsComponent.o: WaterSurfaceGraphicsComponent.cpp.o

.PHONY : WaterSurfaceGraphicsComponent.o

# target to build an object file
WaterSurfaceGraphicsComponent.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurfaceGraphicsComponent.cpp.o
.PHONY : WaterSurfaceGraphicsComponent.cpp.o

WaterSurfaceGraphicsComponent.i: WaterSurfaceGraphicsComponent.cpp.i

.PHONY : WaterSurfaceGraphicsComponent.i

# target to preprocess a source file
WaterSurfaceGraphicsComponent.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurfaceGraphicsComponent.cpp.i
.PHONY : WaterSurfaceGraphicsComponent.cpp.i

WaterSurfaceGraphicsComponent.s: WaterSurfaceGraphicsComponent.cpp.s

.PHONY : WaterSurfaceGraphicsComponent.s

# target to generate assembly for a file
WaterSurfaceGraphicsComponent.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurfaceGraphicsComponent.cpp.s
.PHONY : WaterSurfaceGraphicsComponent.cpp.s

WaterSurfacePhysicsComponent.o: WaterSurfacePhysicsComponent.cpp.o

.PHONY : WaterSurfacePhysicsComponent.o

# target to build an object file
WaterSurfacePhysicsComponent.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurfacePhysicsComponent.cpp.o
.PHONY : WaterSurfacePhysicsComponent.cpp.o

WaterSurfacePhysicsComponent.i: WaterSurfacePhysicsComponent.cpp.i

.PHONY : WaterSurfacePhysicsComponent.i

# target to preprocess a source file
WaterSurfacePhysicsComponent.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurfacePhysicsComponent.cpp.i
.PHONY : WaterSurfacePhysicsComponent.cpp.i

WaterSurfacePhysicsComponent.s: WaterSurfacePhysicsComponent.cpp.s

.PHONY : WaterSurfacePhysicsComponent.s

# target to generate assembly for a file
WaterSurfacePhysicsComponent.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WaterSurfacePhysicsComponent.cpp.s
.PHONY : WaterSurfacePhysicsComponent.cpp.s

WindowParameters.o: WindowParameters.cpp.o

.PHONY : WindowParameters.o

# target to build an object file
WindowParameters.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WindowParameters.cpp.o
.PHONY : WindowParameters.cpp.o

WindowParameters.i: WindowParameters.cpp.i

.PHONY : WindowParameters.i

# target to preprocess a source file
WindowParameters.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WindowParameters.cpp.i
.PHONY : WindowParameters.cpp.i

WindowParameters.s: WindowParameters.cpp.s

.PHONY : WindowParameters.s

# target to generate assembly for a file
WindowParameters.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/WindowParameters.cpp.s
.PHONY : WindowParameters.cpp.s

World.o: World.cpp.o

.PHONY : World.o

# target to build an object file
World.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/World.cpp.o
.PHONY : World.cpp.o

World.i: World.cpp.i

.PHONY : World.i

# target to preprocess a source file
World.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/World.cpp.i
.PHONY : World.cpp.i

World.s: World.cpp.s

.PHONY : World.s

# target to generate assembly for a file
World.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/World.cpp.s
.PHONY : World.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sail-game.dir/build.make CMakeFiles/sail-game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sail-game"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... FileUtils.o"
	@echo "... FileUtils.i"
	@echo "... FileUtils.s"
	@echo "... Line.o"
	@echo "... Line.i"
	@echo "... Line.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... Plane.o"
	@echo "... Plane.i"
	@echo "... Plane.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... PlayerInputComponent.o"
	@echo "... PlayerInputComponent.i"
	@echo "... PlayerInputComponent.s"
	@echo "... PointForce.o"
	@echo "... PointForce.i"
	@echo "... PointForce.s"
	@echo "... RigidObject.o"
	@echo "... RigidObject.i"
	@echo "... RigidObject.s"
	@echo "... RigidObjectGraphicsComponent.o"
	@echo "... RigidObjectGraphicsComponent.i"
	@echo "... RigidObjectGraphicsComponent.s"
	@echo "... ShaderMisc.o"
	@echo "... ShaderMisc.i"
	@echo "... ShaderMisc.s"
	@echo "... SkyParameters.o"
	@echo "... SkyParameters.i"
	@echo "... SkyParameters.s"
	@echo "... SkyboxObject.o"
	@echo "... SkyboxObject.i"
	@echo "... SkyboxObject.s"
	@echo "... SkyboxObjectGraphicsComponent.o"
	@echo "... SkyboxObjectGraphicsComponent.i"
	@echo "... SkyboxObjectGraphicsComponent.s"
	@echo "... TestObject.o"
	@echo "... TestObject.i"
	@echo "... TestObject.s"
	@echo "... Triangle.o"
	@echo "... Triangle.i"
	@echo "... Triangle.s"
	@echo "... TypeSize.o"
	@echo "... TypeSize.i"
	@echo "... TypeSize.s"
	@echo "... UBOManager.o"
	@echo "... UBOManager.i"
	@echo "... UBOManager.s"
	@echo "... VertexElementGraphicsComponent.o"
	@echo "... VertexElementGraphicsComponent.i"
	@echo "... VertexElementGraphicsComponent.s"
	@echo "... WaterSurface.o"
	@echo "... WaterSurface.i"
	@echo "... WaterSurface.s"
	@echo "... WaterSurfaceGraphicsComponent.o"
	@echo "... WaterSurfaceGraphicsComponent.i"
	@echo "... WaterSurfaceGraphicsComponent.s"
	@echo "... WaterSurfacePhysicsComponent.o"
	@echo "... WaterSurfacePhysicsComponent.i"
	@echo "... WaterSurfacePhysicsComponent.s"
	@echo "... WindowParameters.o"
	@echo "... WindowParameters.i"
	@echo "... WindowParameters.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

